### ISSUE TITLE
Unable to install raspi-soft-pwm

### ISSUE THREAD

**Issue by vovchisko** [nebrius/raspi-soft-pwm#6]
Raspberry P4 B with Ubuntu 21.10

![image](https://user-images.githubusercontent.com/295488/149639678-49d104e0-2a2a-4a8a-bb4f-283451cac4c4.png)

Meanwhile, I still can install `pigpio` manually. But it doesn't help.

**Comment by nebrius** [comment]
Hi @vovchisko. The Raspi.js suite only supports Raspbian I'm afraid, not Ubuntu. If you switch to Raspbian, this error should go away.

**Comment by vovchisko** [comment]
Ah, make sense. Thanks for quick response.
Closed.
